package modelo.pojo;
// Generated 01-sep-2018 18:24:08 by Hibernate Tools 4.3.1

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.Formula;

/**
 * Camino generated by hbm2java
 */
@Entity
@Table(name = "camino", schema = "public"
)
public class Camino implements java.io.Serializable {

    private Long id;
    private Long idMapa;
    private Long idNodoFin;
    private Long idNodoInicio;
    private int numero;
    private int numeroNodoFin;
    private int numeroNodoInicio;
    private String codigoNodoFin;
    private String codigoNodoInicio;
    private int peso;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "id_mapa", nullable = false)
    public Long getIdMapa() {
        return idMapa;
    }

    public void setIdMapa(Long idMapa) {
        this.idMapa = idMapa;
    }

    @Column(name = "id_nodo_fin", nullable = false)
    public Long getIdNodoFin() {
        return this.idNodoFin;
    }

    public void setIdNodoFin(Long idNodoFin) {
        this.idNodoFin = idNodoFin;
    }

    @Column(name = "id_nodo_inicio", nullable = false)
    public Long getIdNodoInicio() {
        return this.idNodoInicio;
    }

    public void setIdNodoInicio(Long idNodoInicio) {
        this.idNodoInicio = idNodoInicio;
    }

    @Column(name = "numero", nullable = false)
    public int getNumero() {
        return this.numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    @Formula(value = "(SELECT NOD.numero FROM nodo NOD WHERE NOD.id = id_nodo_fin)")
    @Basic(fetch = FetchType.EAGER)
    public int getNumeroNodoFin() {
        return numeroNodoFin;
    }

    public void setNumeroNodoFin(int numeroNodoFin) {
        this.numeroNodoFin = numeroNodoFin;
    }

    @Formula(value = "(SELECT NOD.numero FROM nodo NOD WHERE NOD.id = id_nodo_inicio)")
    @Basic(fetch = FetchType.EAGER)
    public int getNumeroNodoInicio() {
        return numeroNodoInicio;
    }

    public void setNumeroNodoInicio(int numeroNodoInicio) {
        this.numeroNodoInicio = numeroNodoInicio;
    }

    @Formula(value = "(SELECT NOD.codigo FROM nodo NOD WHERE NOD.id = id_nodo_inicio)")
    @Basic(fetch = FetchType.EAGER)
    public String getCodigoNodoInicio() {
        return codigoNodoInicio;
    }

    public void setCodigoNodoInicio(String codigoNodoInicio) {
        this.codigoNodoInicio = codigoNodoInicio;
    }

    @Formula(value = "(SELECT NOD.codigo FROM nodo NOD WHERE NOD.id = id_nodo_fin)")
    @Basic(fetch = FetchType.EAGER)
    public String getCodigoNodoFin() {
        return codigoNodoFin;
    }

    public void setCodigoNodoFin(String codigoNodoFin) {
        this.codigoNodoFin = codigoNodoFin;
    }

    @Column(name = "peso", nullable = false)
    public int getPeso() {
        return this.peso;
    }

    public void setPeso(int peso) {
        this.peso = peso;
    }

}
