package modelo.pojo;
// Generated 01-sep-2018 18:24:08 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Camino generated by hbm2java
 */
@Entity
@Table(name = "camino", schema = "public"
)
public class Camino implements java.io.Serializable {

    private Long id;
    private Long idMapa;
    private Long idNodoFin;
    private Long idNodoInicio;
    private int peso;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "id_mapa", nullable = false)
    public Long getIdMapa() {
        return idMapa;
    }

    public void setIdMapa(Long idMapa) {
        this.idMapa = idMapa;
    }

    @Column(name = "id_nodo_fin", nullable = false)
    public Long getIdNodoFin() {
        return this.idNodoFin;
    }

    public void setIdNodoFin(Long idNodoFin) {
        this.idNodoFin = idNodoFin;
    }

    @Column(name = "id_nodo_inicio", nullable = false)
    public Long getIdNodoInicio() {
        return this.idNodoInicio;
    }

    public void setIdNodoInicio(Long idNodoInicio) {
        this.idNodoInicio = idNodoInicio;
    }

    @Column(name = "peso", nullable = false)
    public int getPeso() {
        return this.peso;
    }

    public void setPeso(int peso) {
        this.peso = peso;
    }

}
