package modelo.pojo;
// Generated 01-sep-2018 18:24:08 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Camino generated by hbm2java
 */
@Entity
@Table(name="camino"
    ,schema="public"
)
public class Camino  implements java.io.Serializable {


     private long id;
     private Nodo nodoByIdNodoFin;
     private Nodo nodoByIdNodoInicio;
     private int peso;

    public Camino() {
    }

    public Camino(long id, Nodo nodoByIdNodoFin, Nodo nodoByIdNodoInicio, int peso) {
       this.id = id;
       this.nodoByIdNodoFin = nodoByIdNodoFin;
       this.nodoByIdNodoInicio = nodoByIdNodoInicio;
       this.peso = peso;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_nodo_fin", nullable=false)
    public Nodo getNodoByIdNodoFin() {
        return this.nodoByIdNodoFin;
    }
    
    public void setNodoByIdNodoFin(Nodo nodoByIdNodoFin) {
        this.nodoByIdNodoFin = nodoByIdNodoFin;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_nodo_inicio", nullable=false)
    public Nodo getNodoByIdNodoInicio() {
        return this.nodoByIdNodoInicio;
    }
    
    public void setNodoByIdNodoInicio(Nodo nodoByIdNodoInicio) {
        this.nodoByIdNodoInicio = nodoByIdNodoInicio;
    }

    
    @Column(name="peso", nullable=false)
    public int getPeso() {
        return this.peso;
    }
    
    public void setPeso(int peso) {
        this.peso = peso;
    }




}


