package modelo.pojo;
// Generated 01-sep-2018 18:24:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Companhia generated by hbm2java
 */
@Entity
@Table(name="companhia"
    ,schema="public"
)
public class Companhia  implements java.io.Serializable {


     private long id;
     private String nombre;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<Mapa> mapas = new HashSet<Mapa>(0);

    public Companhia() {
    }

	
    public Companhia(long id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Companhia(long id, String nombre, Set<Usuario> usuarios, Set<Mapa> mapas) {
       this.id = id;
       this.nombre = nombre;
       this.usuarios = usuarios;
       this.mapas = mapas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="companhia")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="companhia")
    public Set<Mapa> getMapas() {
        return this.mapas;
    }
    
    public void setMapas(Set<Mapa> mapas) {
        this.mapas = mapas;
    }




}


