package modelo.pojo;
// Generated 01-sep-2018 18:24:08 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Emergencia generated by hbm2java
 */
@Entity
@Table(name="emergencia"
    ,schema="public"
)
public class Emergencia  implements java.io.Serializable {


     private long id;
     private Mapa mapa;
     private Nodo nodo;
     private Date fecha;

    public Emergencia() {
    }

    public Emergencia(long id, Mapa mapa, Nodo nodo, Date fecha) {
       this.id = id;
       this.mapa = mapa;
       this.nodo = nodo;
       this.fecha = fecha;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_mapa", nullable=false)
    public Mapa getMapa() {
        return this.mapa;
    }
    
    public void setMapa(Mapa mapa) {
        this.mapa = mapa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_nodo", nullable=false)
    public Nodo getNodo() {
        return this.nodo;
    }
    
    public void setNodo(Nodo nodo) {
        this.nodo = nodo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false, length=29)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


