package modelo.pojo;
// Generated 01-sep-2018 18:24:08 by Hibernate Tools 4.3.1

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Mapa generated by hbm2java
 */
@Entity
@Table(name = "mapa", schema = "public"
)
public class Mapa implements java.io.Serializable {

    private Long id;
    private Long idCompanhia;
    private Boolean nuevoPath;
    private String path;
    private String contentPath;
    private String nombre;
    private String descripcion;
    private List<Nodo> nodos;
    private List<Camino> caminos;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "id_companhia", nullable = false)
    public Long getIdCompanhia() {
        return this.idCompanhia;
    }

    public void setIdCompanhia(Long idCompanhia) {
        this.idCompanhia = idCompanhia;
    }

    @Transient
    public Boolean getNuevoPath() {
        return nuevoPath;
    }

    public void setNuevoPath(Boolean nuevoPath) {
        this.nuevoPath = nuevoPath;
    }

    @Column(name = "path", nullable = false)
    public String getPath() {
        return this.path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    @Transient
    public String getContentPath() {
        return contentPath;
    }

    public void setContentPath(String contentPath) {
        this.contentPath = contentPath;
    }

    @Column(name = "nombre", nullable = false)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "descripcion", nullable = false)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Transient
    public List<Nodo> getNodos() {
        return nodos;
    }

    public void setNodos(List<Nodo> nodos) {
        this.nodos = nodos;
    }

    @Transient
    public List<Camino> getCaminos() {
        return caminos;
    }

    public void setCaminos(List<Camino> caminos) {
        this.caminos = caminos;
    }

}
