package modelo.pojo;
// Generated 01-sep-2018 18:24:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mapa generated by hbm2java
 */
@Entity
@Table(name="mapa"
    ,schema="public"
)
public class Mapa  implements java.io.Serializable {


     private long id;
     private Companhia companhia;
     private String path;
     private String nombre;
     private String descripcion;
     private Set<Emergencia> emergencias = new HashSet<Emergencia>(0);
     private Set<Nodo> nodos = new HashSet<Nodo>(0);

    public Mapa() {
    }

	
    public Mapa(long id, Companhia companhia, String path, String nombre, String descripcion) {
        this.id = id;
        this.companhia = companhia;
        this.path = path;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Mapa(long id, Companhia companhia, String path, String nombre, String descripcion, Set<Emergencia> emergencias, Set<Nodo> nodos) {
       this.id = id;
       this.companhia = companhia;
       this.path = path;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.emergencias = emergencias;
       this.nodos = nodos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_companhia", nullable=false)
    public Companhia getCompanhia() {
        return this.companhia;
    }
    
    public void setCompanhia(Companhia companhia) {
        this.companhia = companhia;
    }

    
    @Column(name="path", nullable=false)
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }

    
    @Column(name="nombre", nullable=false)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", nullable=false)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mapa")
    public Set<Emergencia> getEmergencias() {
        return this.emergencias;
    }
    
    public void setEmergencias(Set<Emergencia> emergencias) {
        this.emergencias = emergencias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mapa")
    public Set<Nodo> getNodos() {
        return this.nodos;
    }
    
    public void setNodos(Set<Nodo> nodos) {
        this.nodos = nodos;
    }




}


