package modelo.pojo;
// Generated 01-sep-2018 18:24:08 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Nodo generated by hbm2java
 */
@Entity
@Table(name = "nodo", schema = "public"
)
public class Nodo implements java.io.Serializable {

    private Long id;
    private Long idMapa;
    private int numero;
    private String codigo;
    private int x;
    private int y;
    private boolean objetivo;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "id_mapa", nullable = false)
    public Long getIdMapa() {
        return this.idMapa;
    }

    public void setIdMapa(Long idMapa) {
        this.idMapa = idMapa;
    }

    @Column(name = "numero", nullable = false)
    public int getNumero() {
        return numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    @Column(name = "codigo", nullable = false)
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @Column(name = "x", nullable = false)
    public int getX() {
        return this.x;
    }

    public void setX(int x) {
        this.x = x;
    }

    @Column(name = "y", nullable = false)
    public int getY() {
        return this.y;
    }

    public void setY(int y) {
        this.y = y;
    }

    @Column(name = "objetivo", nullable = false)
    public boolean isObjetivo() {
        return this.objetivo;
    }

    public void setObjetivo(boolean objetivo) {
        this.objetivo = objetivo;
    }


}
